config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :workouts do
    resources :exercises
  end

  authenticated :user do
    root 'workouts#index', as: "authenticated_root"
  end

  root 'welcome#index'

#API
  namespace :api do
    resources :workouts
  end

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
  validates :name, :workout_type, :link, :description, presence: true
  validates :name, length: { maximum: 100 }
  validates :workout_type, length: { maximum: 100 }
  validates :link, length: { maximum: 200 }
  validates :description, length: { maximum: 1000 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable,:confirmable
  has_many :workouts, dependent: :destroy
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :exercises, dependent: :destroy
  belongs_to :user
  validates :date, :workout, :length, presence: true
  validates :date, :workout, :rating, :length, length: { maximum: 200 }
end

app/controllers/api/workouts_controller.rb
class Api::WorkoutsController < ApplicationController
  def index
    @workouts = Workout.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:destroy]
  before_filter :authenticate_user!

  def create
    @workout = Workout.find(params[:workout_id])
    exercise = @workout.exercises.create(exercise_params)

    redirect_to workout_path(@workout)
  end

  def destroy
    @workout = @exercise.workout
    @exercise.delete

    redirect_to workout_path(@workout)
  end

  private
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    def exercise_params
      params.require(:exercise).permit(:name, :workout_type, :link, :description, :workout_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"

  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @workouts = Workout.where(user_id: current_user)
  end

  def show
  end

  def new
    @workout = current_user.workouts.build
  end

  def create
    @workout = current_user.workouts.build(workouts_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @workout.update(workouts_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_path
  end

  private

    def workouts_params
      params.require(:workout).permit(:date, :workout, :rating, :length)
    end

    def find_workout
      @workout = Workout.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon_link(glyphicon, link_string)
    ('<i class="' + glyphicon + '"></i>').html_safe + " " + link_string
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.slim
.panel.panel-default
  .panel-heading Lessons
  table.table
    tr
      td.col-md-2
        b Lesson
      td.col-md-2
        b Lesson type
      td.col-md-3
        b Link to lesson
      td.col-md-6
        b Lesson description
      td.col-md-1
        b Delete
    - @workout.exercises.each do |exercise|
      tr.active
        td 
          b = exercise.name
        td = exercise.workout_type
        td = link_to exercise.link, exercise.link
        td = exercise.description
        td = link_to workout_exercise_path(@workout, exercise), method: :delete, class: "btn btn-danger"
          span.glyphicon.glyphicon-erase

app/views/exercises/_form.html.slim
.well.bs-component
  = simple_form_for [@workout, @workout.exercises.build] do |f|
    = f.input :name, class: "from-control"
    = f.input :workout_type, collection: ["ScreenCast", "Online Course", "Post Link"], class: "from-control"
    = f.input :link, class: "from-control"
    = f.input :description, as: :text, class: "from-control"
    = f.button :submit

app/views/layouts/application.html.slim
doctype html
html
  head
    title Workout Application
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to icon_link("glyphicon glyphicon-blackboard", "My lessons"), root_path, class: "navbar-brand"
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li = link_to icon_link("glyphicon glyphicon-plus-sign", "Create Workout"), new_workout_path
            li = link_to icon_link("glyphicon glyphicon-user", "User page"), edit_user_registration_path
            li = link_to icon_link("glyphicon glyphicon-log-out", "Exit"), destroy_user_session_path, :method => :delete
          - else
            li = link_to icon_link("glyphicon glyphicon-log-in", "Sign in"), new_user_session_path
            li = link_to icon_link("glyphicon glyphicon-plus-sign", "Sign up"), new_user_registration_path
    .container
      - if notice
        p.notice = notice
      - if alert
        p.alert = alert
      .col-md-8
        = yield
      .col-md-4
        .panel.panel-primary
          .panel-heading Right panel
          .panel-body Panel body

app/views/layouts/welcome.html.slim
doctype html
html
  head
    title Lessons dashboard
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar-default
      .container
        .navbar-header
          = link_to icon_link("glyphicon glyphicon-blackboard", "My lessons"), root_path, class: "navbar-brand"
    header.image-bg-fluid-height
      p = link_to "Sign in", new_user_session_path, class: "btn btn-primary"
      p = link_to "Sign up", new_user_registration_path, class: "btn btn-success"

    section
      .container
        .row
          .col-lg-12
            h1.section-heading Make your learning easier
            ul
              li Create your own shedule
              li Evaluate your progress
              li Make more
              li ...

    aside.image-bg-fixed-height

    section
      .container
        .row
          .col-lg-12
            h1.section-heading All lessons and courses in one place
    footer
      .container
        .row
          .col-lg-12
            p Copyright &copy; Lessons dashboard 2016

app/views/welcome/index.html.slim
h1 Hello World

app/views/workouts/_form.html.slim
.well.bs-component
  = simple_form_for(@workout, html: { class: 'bs-component' }) do |f|
    = f.input :date, label: "Date"
    = f.input :workout, label: "Workout", class: " form-control"
    = f.input :rating, label: "Rating", class: " form-control"
    = f.input :length, label: "Length", class: " form-control"
    = f.button :submit
  

app/views/workouts/edit.html.slim
h1 Edit workout

= render "form"

= link_to "Cancel", root_path

app/views/workouts/index.html.slim
h1 Lessons List

.panel.panel-default
  table.table
    tr
      td.col-md-3
        b Date
      td.col-md-4
        b Lesson Name
      td.col-md-1
        b Rating
      td.col-md-2
        b Length
      td.col-md-2
        b Actions
    - @workouts.each do |workout|
      tr.active
        td = workout.date.strftime("%A %B %m")
        td = link_to workout.workout, workout
        td = workout.rating
        td = workout.length
        td
          = link_to edit_workout_path(workout), class: "btn btn-success btn-xs"
            span.glyphicon.glyphicon-pencil
          = link_to workout, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs"
            span.glyphicon.glyphicon-remove

app/views/workouts/new.html.slim
h1 Create Lesson

= render "form"

app/views/workouts/show.html.slim
h1 = @workout.workout
.workout
  ul
    li
      b Date: 
      = @workout.date.strftime("%A %B %m")
    li
      b Rating: 
      = @workout.rating
    li
      b Length: 
      = @workout.length
.btn-group
  = link_to "Back", root_path, class: "btn btn-default" 
  = link_to "Edit", edit_workout_path(@workout), class: "btn btn-success" 
  = link_to "Destroy", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" 

p#exercises
  = render "exercises/exercise"
  = render "exercises/form"